/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IHero, IHeroInterface } from "../../../contracts/Hero.sol/IHero";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "hero_type",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IHero__factory {
  static readonly abi = _abi;
  static createInterface(): IHeroInterface {
    return new Interface(_abi) as IHeroInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IHero {
    return new Contract(address, _abi, runner) as unknown as IHero;
  }
}
